version: '3.3'

services: 
    wordpress:
        build: .docker/wordpress/.
        restart: always
        ports: 
            - 81:80
        environment: 
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wpuser
            WORDPRESS_DB_PASSWORD: wppass
            WORDPRESS_DB_NAME: wpdb
        volumes: 
            - ./src/plugins:/var/www/html/wp-content/plugins
            - ./src/themes:/var/www/html/wp-content/themes

    db:
        image: mysql:5.7
        restart: always
        ports:
            - 3306:3306
        environment: 
            MYSQL_DATABASE: wpdb
            MYSQL_USER: wpuser
            MYSQL_PASSWORD: wppass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes: 
            - db:/var/lib/mysql

    adminer:
        depends_on: 
            - db
        image: adminer
        restart: always
        ports: 
            - 8080:8080

networks: 
    back:
        
volumes: 
    db:
